### ISSUE TITLE
eduPikaViewModel.jsが更新されたらブラウザを自動リロードする

### ISSUE THREAD

**Issue by YSawabe** [edu-pika/web-dojo#11]
eduPikaViewModel.jsが更新されたら毎回自分でリロードさせないといけないのは何かと面倒なので（ものぐさなのでw）自動リロード（BrowserSync）するようにしてください。
「gulp」「browser-sync」などのキーワードで調べるとおそらく対応できると思います。

**Comment by SQUARE-horse** [comment]
SourceTreeの樹形図がおかしい件について対応しようと思いましたが、希望する形と変更する方法が分からなくなってしまいました。
チェリーピックについては調べたのですが、今回はどのように使えば良いのか分からなかったので、明日などに相談させてください。

参考サイト：http://tech.aainc.co.jp/archives/5438

**Comment by SQUARE-horse** [comment]
SourceTreeの樹形図を戻そうとしたのですが、以前教えていただいた通りにknockout2というブランチを切ってチェリーピックを使ったのですがうまく行きませんでした。
おそらく何らかの手順が抜けてしまったためと思うのですが、masterの方を何かコミットしたら正常になったため、特に意味のないコミットをして直しました。

**Comment by YSawabe** [comment]
うーんと。
masterにコミットしたらknockout2ブランチを切ってチェリーピックができるようになった理由はよくわからないですが、そもそもの話、knockout2ブランチのベースがコミット「9375821」になっています。
SourceTreeの樹形図がおかしい件で直して欲しかったのは「4ed493c」からブランチを作って欲しかったので（今は意味のないコミットが入ってしまっているので「592b4cb」からブランチを作るしか無くなっていますが。。。）現時点での最新のマスターからブランチを作り直してください。
もし、チェリーピックができないのであれば、手動でコードをマージしてください。今回はそんなに修正もないですので、大した作業ではないと思います。
チェリーピックはあくまで手段なので、それに固執する必要はないですよ。
（まぁ、おそらくできなかったのはローカルリポジトリが何かおかしい状態になってたからだと思います）
