### ISSUE TITLE
開発ツールを自分の環境にインストールして手順をREADMEに記載する

### ISSUE THREAD

**Issue by YSawabe** [edu-pika/web-dojo#3]
下記の開発ツールを自分の環境にインストールする
- SourceTree
- Atom

README.mdの開発環境を更新し、上記ツールのインストール方法を追記する。
README.mdを修正したらプルリクを出す。

**Comment by SQUARE-horse** [comment]
SourceTree、Atomのインストール、およびREADME.mdの追記について完了いたしました。

しかし、README.mdを修正したらプルリクを出す件について問題が発生しております。
SourceTree上でgithubのURLを指定してクローンを作成し、変更内容をpushしようとしたのですが、以下のエラーが発生しました。

> git -c diff.mnemonicprefix=false -c core.quotepath=false push -v --tags --set-upstream origin readme:readme
> Fatal: ArgumentException encountered.
> 
> remote: Permission to edu-pika/web-dojo.git denied to SQUARE-horse.
> 
> fatal: unable to access 'https://github.com/edu-pika/web-dojo.git/': The requested URL returned error: 403
> 
> Pushing to https://github.com/edu-pika/web-dojo.git
> 
> エラー終了しました。エラーの内容は上記をご覧ください。

少し調べてみたところ、指定するURLがhttpsのものではなくsshを用いなければならないという記述を見つけました。　http://qiita.com/kyanro@github/items/60a9dc5a32ed1562fec2
上記のサイトの通りにやったつもりなのですが、sshを用いたクローンが成功せず、エラーが発生してしまいます。

> git -c filter.lfs.smudge= -c filter.lfs.required=false -c diff.mnemonicprefix=false -c core.quotepath=false clone --recursive git@github.com:edu-pika/web-dojo.git C:\Users\user\Documents\web-dojo
> fatal: destination path 'C:\Users\user\Documents\web-dojo' already exists and is not an empty directory.
> 
> エラー終了しました。エラーの内容は上記をご覧ください。

お手数掛けますが、どこで間違っているか教えていただければと思います。

**Comment by YSawabe** [comment]
おそらく、権限がないのでエラーになっているようですね。

> fatal: unable to access 'https://github.com/edu-pika/web-dojo.git/': The requested URL returned error: 403

厳密には、ユーザーが特定できていないので権限エラーになってしまっているようです。実は私もこれで少しハマりました（汗）
クローンするURLに自分のユーザー名を追加してみてください。

https://SQUARE-horse@github.com/edu-pika/web-dojo.git

おそらく、上記のように変更すると初回アクセスする際にパスワードが聞かれると思います。その後はパスワードがキャッシュされるのでパスワードを入れなくてもプッシュなどできるようになるはずです。

sourcetreeを使っているのであれば、対象のリポジトリタブを選んで右上の「設定」ボタンを押すとリモートリポジトリのパスを変更できるはずです。

**Comment by SQUARE-horse** [comment]
権限エラーについて教えていただき、ありがとうございました。
しかし、ご指定いただいたURLの「https://SQUARE-horse@github.com/edu-pika/web-dojo.git」では同様のエラーが発生してしまいました。

指定のするURLを「https://github.com/SQUARE-horse/web-dojo.git」に変えるとpushすることができたのですが、問題は無いでしょうか？
また、恐らくプルリクエストもできたと思うのですがいかがでしょうか？

**Comment by YSawabe** [comment]
「https://github.com/SQUARE-horse/web-dojo.git」
ですがこれだと、別のリポジトリにプッシュしてしまっているので残念ながらNGです。「SQUARE-horse」ユーザーの「web-dojo」というリポジトリにプッシュしています。
なので、「edu-pika/web-dojo.git」にプッシュお願いします。

で、権限周りを調べていたところ、「edu-pika」チームに所属しているメンバーのデフォルト権限が「read」になっていました。これだとcloneやpullしかできないようで「write」権限に変更してみました。もう一度「https://SQUARE-horse@github.com/edu-pika/web-dojo.git」で試してみてもらえますか？

プルリクもおかしなことになってしまっているので一回出しなおしてもらってもいいですか？一旦今上がっているものはクローズしますね。

**Comment by SQUARE-horse** [comment]
git-hub側の権限の問題だったんですね。
「https://SQUARE-horse@github.com/edu-pika/web-dojo.git」の方でプルリクエストが出来たと思いますので、ご確認いただけますでしょうか。

**Comment by YSawabe** [comment]
やはり権限の問題でしたか。設定見落としてました。こちらこそゴメンなさい。。。
プルリク確認しておきます。
